### ISSUE TITLE
How do I create the static site if I modify the web site code?

### ISSUE THREAD

**Issue by kdahlquist** [kdahlquist/DahlquistLab#10]
@dondi, if I make changes to the code for my web site, how do I make the static page so I can deploy it on myweb?

**Comment by dondi** [comment]
As far as I can tell based on the file layout, upon changing the code (presumably you are editing what is in the _/site_ folder), you need to run Jekyll within that folder. Windows installation is documented at http://jekyllrb.com/docs/windows/#installation —this takes multiple steps because Jekyll relies on multiple packages, but the basic requirement is Ruby. There are steps for enabling syntax-highlighting, but I don’t think you’ll need those for the Lab website, so I would suggest skipping those unless the subsequent Jekyll command does not work.

Jekyll, upon running (specific command: `jekyll build`), will generate the website in the _/site/_static_site_ folder. It is the contents of _this_ folder that mirrors the _myweb_ site; this can then be FTP'ed as-is to the _myweb_ server.

**Comment by kdahlquist** [comment]
@dondi, I have made all of the changes to the site I want to do for now and have merged them into the master branch.  It is ready for you to run Jekyll at your convenience.  Thanks.

I don't really have a good way to preview the site to see if I messed anything up, so I'm hoping it looks OK.

**Comment by dondi** [comment]
I regenerated the files under __static_site_ and gave them a quick eyeball before committing and pushing. No issues stuck out to me, but admittedly this was a quick click-through.

If you pull or download the latest copy of this repository, then upload __static_site_ to _myweb_, then this should update things over there.

I deemed it safe to commit and push directly to `master` because the only change was to have Jekyll regenerate the static files based on the existing source.

**Comment by kdahlquist** [comment]
Thank you.  I deployed the static site.  It looks OK, but there are some minor formatting issues (bold, centering, etc.) that I messed up.  I'll have to fix them later and ask you to redo the Jekyll.  It's not urgent so it may be a while before I get to it again.  For the moment, I'll close this issue.
