### ISSUE TITLE
Chancery-like font did not transfer when deployed site

### ISSUE THREAD

**Issue by kdahlquist** [kdahlquist/DahlquistLab#3]
I tried deploying the site (I took it back down again) today and saw that the chancery-like font did not deploy.

**Comment by NAnguiano** [comment]
The issue causing this is that the font I used comes pre-installed on most macs. As a result, it appeared on my screen, but would not appear on a screen in which the font was not installed. I found a font that I think looks nice that I could get to appear on every screen due to being able to link to the font through google fonts. Here's what the font looks like:

![fontpic](https://cloud.githubusercontent.com/assets/6444156/9982343/7a68c2c2-5f8d-11e5-9710-55cdd551f37c.png)

Let me know what you think. Google fonts offers a lot of different fonts so there are many options.

**Comment by dondi** [comment]
You can investigate including Web fonts (.woff files) or TrueType fonts (.ttf fonts) as part of the source upload. If you look at the new LMU website you will see a "Franklin ITC" font being used, as included by the website itself. One difference in myweb.lmu.edu is that the server there does not appear to recognize the .woff extension. For that, you'll need to include a .ttf font. Again, see the new LMU website for how the font is expressed in CSS. That site does handle .woff OK, but the CSS nonetheless specifies a .ttf alternate just in case.

**Comment by kdahlquist** [comment]
Here are some chancery-like fonts:
http://www.1001fonts.com/itc-zapf-chancery-fonts.html

chancery script medium on this page: http://www.fonts101.com/search/Chancery

Maybe these ones from google: Italianno or Quintessential or Felipa

If you could let me know if either of the top two are viable, I think I would prefer one of them.  For the google fonts, if you can just give me a preview of what "Dahlquist Lab" would look like with each of them, that would be appreciated.  Thanks.

**Comment by kdahlquist** [comment]
Closing this because after >1 year, I'm not going to bother to change the font.
